### ISSUE TITLE
2017/R/dgp heteroskedastic errors fixed?

### ISSUE THREAD

**Issue by thisisreallife** [vdorie/aciccomp#2]
In [Atlantic Causal Inference Conference (ACIC) Data Analysis Challenge 2017(P. Richard Hahn∗
, Vincent Dorie, and Jared S. Murray, 2019)](https://arxiv.org/pdf/1905.09515.pdf)：

1. Author noted that `there is an error in the data files generated with heteroskedastic errors.`. However, I checked `2017/R/dgp.R`, I think the error is fixed. Am I right?

2. Author provided scripts for two methods(Bayesian Causal Forest and Gradient random forest), named `bcf.att.R` and `grf.att.R` . However, I didn't find it in 2017 repository. Maybe files are missed?

**Comment by vdorie** [comment]
1. Yes, the error is fixed in the repository.
2. I don't know where those files were supposed to be hosted. I have them locally and I can share them over email, however `bcf` is now its own package on CRAN.
